emse_platform_advert:
    resource: "@EMSEPlatformBundle/Controller/AdvertController.php"
    type:     annotation

emse_platform_application:
    resource: "@EMSEPlatformBundle/Controller/ApplicationController.php"
    type:     annotation

emse_platform:
    resource: "@EMSEPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform
